<!doctype html>
    <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
    <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
    <!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
    <!--[if gt IE 8]><!--> <html class="no-js" lang="nl"> <!--<![endif]-->
    <head>
        <meta charset="<?php echo $this->meta->Encoding(); ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="robots" content="index, follow" />
		<?php echo $this->meta->Title($title, ''); ?>
		<?php echo $this->meta->Description($description); ?>
		<?php echo $this->meta->Author(); ?>
		<?php echo $this->meta->Twitter(); ?>
		<meta name="google-site-verification" content="" />
		<?php echo $this->meta->GooglePlus(); ?>
		<?php echo $this->meta->OpenGraph(); ?>
		<?php echo $this->meta->Favicon('/public/img/favicon', '#ffffff', '#ffffff', '#ffffff'); ?>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
        <link rel="stylesheet" href="/public/css/style.css">
        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="js/vendor/html5shiv.js"><\/script>')</script>
        <![endif]-->
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
		<header>
			
		</header>
		<section class="container">
			<?php $this->messenger->getMessage(); ?>
			<?php echo $this->renderContent(); ?>
		</section>
		<footer class="text-xs-center">
			
		</footer>
        <!-- JAVASCRIPT -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/jquery-1.11.2.min.js"><\/script>')</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>
        <script src="/public/js/init.js"></script>
        <?php echo $this->meta->GoogleAnalytics(); ?>
    </body>
</html>